### ISSUE TITLE
Failed to load external module coffeescript/register

### ISSUE THREAD

**Issue by daslicht** [jhorology/gulp-nks-replace-mapping#1]
when i run npm install i get 

[12:30:25] Failed to load external module coffeescript/register

idea?

**Comment by jhorology** [comment]
you should install "coffeescript" instead of "coffee-script" in your project.
```
npm install coffeescript --save-dev
```

**Comment by daslicht** [comment]
ok i diondt install it explicit , i just ran npm install .
Thanks !
